project:
  type: book
  output-dir: docs
  render:
    - index.qmd
    - 08 - Hypothesis_Test_z-Scores.qmd
    - 09 - Single-Sample_t-Tests.qmd
    - 10 - Independent-Samples_t-Tests.qmd
    - 11 - Dependent-Samples_t-Tests.qmd
    - 12 - one-way_ANOVA.qmd
    - 13 - repeated-measures_ANOVA.qmd
    - 14 - factorial_ANOVA.qmd
   
book:
  title: "Satistics Problem Generator"
  author: Guenther, Benjamin A.
  date: last-modified # or today
  date-format: YYYY-MM-DD
  site-url: "https://bsts-projects.github.io/pystats/"
  navbar: 
    right: 
      - icon: github
        href: https://github.com/bsts-projects/psystats
        aria-label: GitHub
  chapters:
    - index.qmd
    - 08 - Hypothesis_Test_z-Scores.qmd
    - 09 - Single-Sample_t-Tests.qmd
    - 10 - Independent-Samples_t-Tests.qmd
    - 11 - Dependent-Samples_t-Tests.qmd
    - 12 - one-way_ANOVA.qmd
    - 13 - repeated-measures_ANOVA.qmd
    - 14 - factorial_ANOVA.qmd

format:
  html: 
    theme: cosmo

execute: 
  freeze: auto